# Generated by Django 5.1.7 on 2026-02-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AddField(
            model_name='scan',
            name='risk_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='scan',
            name='security_grade',
            field=models.CharField(default='A', max_length=5),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='impact_analysis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
