# Generated by Django 5.1.7 on 2026-02-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_vulnerability_code_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='total_files_scanned',
            field=models.IntegerField(default=0),
        ),
    ]
